### ISSUE TITLE
É uma péssima prática suprimir todos os warnings

### ISSUE THREAD

**Issue by manoelcampos** [danilorocha22/StrategyProcessarBoletos#1]
Não tem relação com a tarefa, mas suprimir warnings deve ser exceção (e apenas para uma ou outra). Vc tá suprimindo tudo com frequência. Se tem warnings, vc deveria verificar e tentar resolver.

https://github.com/danilorocha22/StrategyProcessarBoletos/blob/f7cd8308ea36445281ea25d6a1a4a4f46f74e60e/src/main/java/strategy/LeituraRetornoBancoBradesco.java#L12

**Comment by danilorocha22** [comment]
Ok professor, obg. Eu estava fazendo isso por que Intellij sublinha todos os nomes das variáveis, deixando o visual um pouco poluído.

**Comment by danilorocha22** [comment]
> Não tem relação com a tarefa, mas suprimir avisos deve ser exceção (e apenas para uma ou outra). Vc tá suprimindo tudo com frequência. Se tem warnings, vc Verificar e tentar resolver.
> 
> https://github.com/danilorocha22/StrategyProcessarBoletos/blob/f7cd8308ea36445281ea25d6a1a4a4f46f74e60e/src/main/java/strategy/LeituraRetornoBancoBradesco.java#L12

Ok professor, obg. Eu estava fazendo isso por que Intellij definem todos os nomes das variáveis, deixando o visual um pouco poluído.

**Comment by danilorocha22** [comment]
> Não tem relação com a tarefa, mas suprimir avisos deve ser exceção (e apenas para uma ou outra). Vc tá suprimindo tudo com frequência. Se tem warnings, vc Verificar e tentar resolver.
> 
> https://github.com/danilorocha22/StrategyProcessarBoletos/blob/f7cd8308ea36445281ea25d6a1a4a4f46f74e60e/src/main/java/strategy/LeituraRetornoBancoBradesco.java#L12

Ok professor, obg. Eu estava fazendo isso por que Intellij sublinha todos os nomes das variáveis, deixando o visual um pouco poluído.

**Comment by manoelcampos** [comment]
Ele sublinha todas as variáveis que não são `final`, para indicar que elas podem ter seu valor alterado.
Para variáveis locais por exemplo, a alteração de valores nelas é com frequência uma fonte de bugs.
Em programação funcional por exemplo, temos o conceito de "Imutabilidade", onde variáveis locais não podem ser alteradas dentro de uma função.

Imutabilidade é um tema extenso e que pode levar um tempo até entender o porquê devemos buscar este princípio.
De qualquer forma, isto é configurado no IntelliJ. Você pode desabilitar isso digitando na tela de preferências "reassigned local variable"

**Comment by danilorocha22** [comment]
> Ele sublinha todas as variáveis que não são `final`, para indicar que elas podem ter seu valor alterado.
> Para variáveis locais por exemplo, a alteração de valores nelas é com frequência uma fonte de bugs.
> Em programação funcional por exemplo, temos o conceito de "Imutabilidade", onde variáveis locais não podem ser alteradas dentro de uma função.
> 
> Imutabilidade é um tema extenso e que pode levar um tempo até entender o porquê devemos buscar este princípio.
> De qualquer forma, isto é configurado no IntelliJ. Você pode desabilitar isso digitando na tela de preferências "reassigned local variable"

Nossa professor, sobre imutabilidade já estudei um pouco, mas não fazia ideia que esse era o motivo, obg pela informação.
